### ISSUE TITLE
main.py 示例文件中无法正确运行

### ISSUE THREAD

**Issue by bop-lp** [LagrangeDev/lagrange-python#50]
[qq.md](https://github.com/user-attachments/files/17929392/qq.md)

**Comment by Decrabbityyy** [comment]
yet, you should set your Environment variables `LAGRANGE_SIGN_URL` to the correct signature address

**Comment by Decrabbityyy** [comment]
It uses the same signature address as Lagrange.Core

**Comment by bop-lp** [comment]
哦，可以了，使用了 https://lagrangedev.github.io/LagrangeGo/guide/sign 的签名，现在已经可以了
感谢大佬
